// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// sfacpp_internal
Rcpp::List sfacpp_internal(const Rcpp::NumericVector& y_, const Rcpp::NumericMatrix& allData_, const Rcpp::IntegerVector& colCounts_, Rcpp::Nullable<Rcpp::IntegerVector> idVec_, Rcpp::Nullable<Rcpp::IntegerVector> timeVec_, Rcpp::Nullable<Rcpp::NumericVector> startVals_, const int prodCost, const std::string& model, const std::string& dist, const std::string& method, const std::string& methodLib, const std::string& marginalEffect, Rcpp::Nullable<Rcpp::List> optimOpts, Rcpp::Nullable<std::vector<std::string>> termsX_, Rcpp::Nullable<std::vector<std::string>> termsZmuit_, Rcpp::Nullable<std::vector<std::string>> termsZuit_, Rcpp::Nullable<std::vector<std::string>> termsZvit_, Rcpp::Nullable<std::vector<std::string>> termsZui0_, Rcpp::Nullable<std::vector<std::string>> termsZvi0_, const unsigned int nsim, const std::string& hessianCalc, const unsigned int hessianCalcNumApproxAccuracy, const int seed, const double confidenceLevel, const bool estimateMarginalEffects, const bool estimateMargEffCI, const unsigned int marginalEffectBootstrapReps, const unsigned int printLevel, const bool clusteredSE, const int haltonBase, const int haltonBurnin, const int haltonUi0Base, const bool scrambledHalton, const bool shuffledHalton, const int nthreads, const bool calculateEfficiencyScores, const int ghkSimReps, const int displayDecimalPlaces, const int displayConsoleWidth, Rcpp::Nullable<std::string> idColName, Rcpp::Nullable<std::string> timeColName);
RcppExport SEXP _sfacpp_sfacpp_internal(SEXP y_SEXP, SEXP allData_SEXP, SEXP colCounts_SEXP, SEXP idVec_SEXP, SEXP timeVec_SEXP, SEXP startVals_SEXP, SEXP prodCostSEXP, SEXP modelSEXP, SEXP distSEXP, SEXP methodSEXP, SEXP methodLibSEXP, SEXP marginalEffectSEXP, SEXP optimOptsSEXP, SEXP termsX_SEXP, SEXP termsZmuit_SEXP, SEXP termsZuit_SEXP, SEXP termsZvit_SEXP, SEXP termsZui0_SEXP, SEXP termsZvi0_SEXP, SEXP nsimSEXP, SEXP hessianCalcSEXP, SEXP hessianCalcNumApproxAccuracySEXP, SEXP seedSEXP, SEXP confidenceLevelSEXP, SEXP estimateMarginalEffectsSEXP, SEXP estimateMargEffCISEXP, SEXP marginalEffectBootstrapRepsSEXP, SEXP printLevelSEXP, SEXP clusteredSESEXP, SEXP haltonBaseSEXP, SEXP haltonBurninSEXP, SEXP haltonUi0BaseSEXP, SEXP scrambledHaltonSEXP, SEXP shuffledHaltonSEXP, SEXP nthreadsSEXP, SEXP calculateEfficiencyScoresSEXP, SEXP ghkSimRepsSEXP, SEXP displayDecimalPlacesSEXP, SEXP displayConsoleWidthSEXP, SEXP idColNameSEXP, SEXP timeColNameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type y_(y_SEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type allData_(allData_SEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type colCounts_(colCounts_SEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type idVec_(idVec_SEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type timeVec_(timeVec_SEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type startVals_(startVals_SEXP);
    Rcpp::traits::input_parameter< const int >::type prodCost(prodCostSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type model(modelSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type dist(distSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type method(methodSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type methodLib(methodLibSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type marginalEffect(marginalEffectSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type optimOpts(optimOptsSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<std::vector<std::string>> >::type termsX_(termsX_SEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<std::vector<std::string>> >::type termsZmuit_(termsZmuit_SEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<std::vector<std::string>> >::type termsZuit_(termsZuit_SEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<std::vector<std::string>> >::type termsZvit_(termsZvit_SEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<std::vector<std::string>> >::type termsZui0_(termsZui0_SEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<std::vector<std::string>> >::type termsZvi0_(termsZvi0_SEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type nsim(nsimSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type hessianCalc(hessianCalcSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type hessianCalcNumApproxAccuracy(hessianCalcNumApproxAccuracySEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< const double >::type confidenceLevel(confidenceLevelSEXP);
    Rcpp::traits::input_parameter< const bool >::type estimateMarginalEffects(estimateMarginalEffectsSEXP);
    Rcpp::traits::input_parameter< const bool >::type estimateMargEffCI(estimateMargEffCISEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type marginalEffectBootstrapReps(marginalEffectBootstrapRepsSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type printLevel(printLevelSEXP);
    Rcpp::traits::input_parameter< const bool >::type clusteredSE(clusteredSESEXP);
    Rcpp::traits::input_parameter< const int >::type haltonBase(haltonBaseSEXP);
    Rcpp::traits::input_parameter< const int >::type haltonBurnin(haltonBurninSEXP);
    Rcpp::traits::input_parameter< const int >::type haltonUi0Base(haltonUi0BaseSEXP);
    Rcpp::traits::input_parameter< const bool >::type scrambledHalton(scrambledHaltonSEXP);
    Rcpp::traits::input_parameter< const bool >::type shuffledHalton(shuffledHaltonSEXP);
    Rcpp::traits::input_parameter< const int >::type nthreads(nthreadsSEXP);
    Rcpp::traits::input_parameter< const bool >::type calculateEfficiencyScores(calculateEfficiencyScoresSEXP);
    Rcpp::traits::input_parameter< const int >::type ghkSimReps(ghkSimRepsSEXP);
    Rcpp::traits::input_parameter< const int >::type displayDecimalPlaces(displayDecimalPlacesSEXP);
    Rcpp::traits::input_parameter< const int >::type displayConsoleWidth(displayConsoleWidthSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<std::string> >::type idColName(idColNameSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<std::string> >::type timeColName(timeColNameSEXP);
    rcpp_result_gen = Rcpp::wrap(sfacpp_internal(y_, allData_, colCounts_, idVec_, timeVec_, startVals_, prodCost, model, dist, method, methodLib, marginalEffect, optimOpts, termsX_, termsZmuit_, termsZuit_, termsZvit_, termsZui0_, termsZvi0_, nsim, hessianCalc, hessianCalcNumApproxAccuracy, seed, confidenceLevel, estimateMarginalEffects, estimateMargEffCI, marginalEffectBootstrapReps, printLevel, clusteredSE, haltonBase, haltonBurnin, haltonUi0Base, scrambledHalton, shuffledHalton, nthreads, calculateEfficiencyScores, ghkSimReps, displayDecimalPlaces, displayConsoleWidth, idColName, timeColName));
    return rcpp_result_gen;
END_RCPP
}
// sfacpp_internal_searches
Rcpp::List sfacpp_internal_searches(const Rcpp::NumericVector& y_, const Rcpp::NumericMatrix& allData_, const Rcpp::IntegerVector& colCounts_, Rcpp::Nullable<Rcpp::IntegerVector> idVec_, Rcpp::Nullable<Rcpp::IntegerVector> timeVec_, Rcpp::Nullable<Rcpp::NumericVector> startVals_, const int reps, const int maxRepIter, const double slengthFrontier, const double slengthSigmas, const int maxStartValFindAttempt, const int prodCost, const std::string& model, const std::string& dist, const std::string& method, const std::string& methodLib, const unsigned int nsim, const int seed, const unsigned int printLevel, const int nthreads, const int haltonBase, const int haltonBurnin, const int haltonUi0Base, const bool scrambledHalton, const bool shuffledHalton, const int displayConsoleWidth, const int displayDecimalPlaces);
RcppExport SEXP _sfacpp_sfacpp_internal_searches(SEXP y_SEXP, SEXP allData_SEXP, SEXP colCounts_SEXP, SEXP idVec_SEXP, SEXP timeVec_SEXP, SEXP startVals_SEXP, SEXP repsSEXP, SEXP maxRepIterSEXP, SEXP slengthFrontierSEXP, SEXP slengthSigmasSEXP, SEXP maxStartValFindAttemptSEXP, SEXP prodCostSEXP, SEXP modelSEXP, SEXP distSEXP, SEXP methodSEXP, SEXP methodLibSEXP, SEXP nsimSEXP, SEXP seedSEXP, SEXP printLevelSEXP, SEXP nthreadsSEXP, SEXP haltonBaseSEXP, SEXP haltonBurninSEXP, SEXP haltonUi0BaseSEXP, SEXP scrambledHaltonSEXP, SEXP shuffledHaltonSEXP, SEXP displayConsoleWidthSEXP, SEXP displayDecimalPlacesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type y_(y_SEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type allData_(allData_SEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type colCounts_(colCounts_SEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type idVec_(idVec_SEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type timeVec_(timeVec_SEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type startVals_(startVals_SEXP);
    Rcpp::traits::input_parameter< const int >::type reps(repsSEXP);
    Rcpp::traits::input_parameter< const int >::type maxRepIter(maxRepIterSEXP);
    Rcpp::traits::input_parameter< const double >::type slengthFrontier(slengthFrontierSEXP);
    Rcpp::traits::input_parameter< const double >::type slengthSigmas(slengthSigmasSEXP);
    Rcpp::traits::input_parameter< const int >::type maxStartValFindAttempt(maxStartValFindAttemptSEXP);
    Rcpp::traits::input_parameter< const int >::type prodCost(prodCostSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type model(modelSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type dist(distSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type method(methodSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type methodLib(methodLibSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type nsim(nsimSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type printLevel(printLevelSEXP);
    Rcpp::traits::input_parameter< const int >::type nthreads(nthreadsSEXP);
    Rcpp::traits::input_parameter< const int >::type haltonBase(haltonBaseSEXP);
    Rcpp::traits::input_parameter< const int >::type haltonBurnin(haltonBurninSEXP);
    Rcpp::traits::input_parameter< const int >::type haltonUi0Base(haltonUi0BaseSEXP);
    Rcpp::traits::input_parameter< const bool >::type scrambledHalton(scrambledHaltonSEXP);
    Rcpp::traits::input_parameter< const bool >::type shuffledHalton(shuffledHaltonSEXP);
    Rcpp::traits::input_parameter< const int >::type displayConsoleWidth(displayConsoleWidthSEXP);
    Rcpp::traits::input_parameter< const int >::type displayDecimalPlaces(displayDecimalPlacesSEXP);
    rcpp_result_gen = Rcpp::wrap(sfacpp_internal_searches(y_, allData_, colCounts_, idVec_, timeVec_, startVals_, reps, maxRepIter, slengthFrontier, slengthSigmas, maxStartValFindAttempt, prodCost, model, dist, method, methodLib, nsim, seed, printLevel, nthreads, haltonBase, haltonBurnin, haltonUi0Base, scrambledHalton, shuffledHalton, displayConsoleWidth, displayDecimalPlaces));
    return rcpp_result_gen;
END_RCPP
}
// sfacpp_internal_lrtest
Rcpp::List sfacpp_internal_lrtest(const double ll0, const double ll1, const int nparam0, const int nparam1, const double dp);
RcppExport SEXP _sfacpp_sfacpp_internal_lrtest(SEXP ll0SEXP, SEXP ll1SEXP, SEXP nparam0SEXP, SEXP nparam1SEXP, SEXP dpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type ll0(ll0SEXP);
    Rcpp::traits::input_parameter< const double >::type ll1(ll1SEXP);
    Rcpp::traits::input_parameter< const int >::type nparam0(nparam0SEXP);
    Rcpp::traits::input_parameter< const int >::type nparam1(nparam1SEXP);
    Rcpp::traits::input_parameter< const double >::type dp(dpSEXP);
    rcpp_result_gen = Rcpp::wrap(sfacpp_internal_lrtest(ll0, ll1, nparam0, nparam1, dp));
    return rcpp_result_gen;
END_RCPP
}
// sfacpp_internal_call_print_model_summary
void sfacpp_internal_call_print_model_summary(const std::string& model, const std::string& dist, const int nobs, const int nids, const int maxT, const int minT, const Rcpp::NumericMatrix& modelSummaryIn, const std::vector<std::string>& modelSummaryTerms, Rcpp::Nullable<Rcpp::List> sigmaParams, const int nsim, const double llscore, const double gnorm, const bool clusteredSE, const int haltonBase, const int haltonBurnin, const int haltonUi0Base, const bool scrambledHalton, const bool shuffledHalton, const double confInt, const int decimalPlaces, const int consoleWidth, Rcpp::Nullable<std::string> idColName, Rcpp::Nullable<std::string> timeColName);
RcppExport SEXP _sfacpp_sfacpp_internal_call_print_model_summary(SEXP modelSEXP, SEXP distSEXP, SEXP nobsSEXP, SEXP nidsSEXP, SEXP maxTSEXP, SEXP minTSEXP, SEXP modelSummaryInSEXP, SEXP modelSummaryTermsSEXP, SEXP sigmaParamsSEXP, SEXP nsimSEXP, SEXP llscoreSEXP, SEXP gnormSEXP, SEXP clusteredSESEXP, SEXP haltonBaseSEXP, SEXP haltonBurninSEXP, SEXP haltonUi0BaseSEXP, SEXP scrambledHaltonSEXP, SEXP shuffledHaltonSEXP, SEXP confIntSEXP, SEXP decimalPlacesSEXP, SEXP consoleWidthSEXP, SEXP idColNameSEXP, SEXP timeColNameSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type model(modelSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type dist(distSEXP);
    Rcpp::traits::input_parameter< const int >::type nobs(nobsSEXP);
    Rcpp::traits::input_parameter< const int >::type nids(nidsSEXP);
    Rcpp::traits::input_parameter< const int >::type maxT(maxTSEXP);
    Rcpp::traits::input_parameter< const int >::type minT(minTSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type modelSummaryIn(modelSummaryInSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type modelSummaryTerms(modelSummaryTermsSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type sigmaParams(sigmaParamsSEXP);
    Rcpp::traits::input_parameter< const int >::type nsim(nsimSEXP);
    Rcpp::traits::input_parameter< const double >::type llscore(llscoreSEXP);
    Rcpp::traits::input_parameter< const double >::type gnorm(gnormSEXP);
    Rcpp::traits::input_parameter< const bool >::type clusteredSE(clusteredSESEXP);
    Rcpp::traits::input_parameter< const int >::type haltonBase(haltonBaseSEXP);
    Rcpp::traits::input_parameter< const int >::type haltonBurnin(haltonBurninSEXP);
    Rcpp::traits::input_parameter< const int >::type haltonUi0Base(haltonUi0BaseSEXP);
    Rcpp::traits::input_parameter< const bool >::type scrambledHalton(scrambledHaltonSEXP);
    Rcpp::traits::input_parameter< const bool >::type shuffledHalton(shuffledHaltonSEXP);
    Rcpp::traits::input_parameter< const double >::type confInt(confIntSEXP);
    Rcpp::traits::input_parameter< const int >::type decimalPlaces(decimalPlacesSEXP);
    Rcpp::traits::input_parameter< const int >::type consoleWidth(consoleWidthSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<std::string> >::type idColName(idColNameSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<std::string> >::type timeColName(timeColNameSEXP);
    sfacpp_internal_call_print_model_summary(model, dist, nobs, nids, maxT, minT, modelSummaryIn, modelSummaryTerms, sigmaParams, nsim, llscore, gnorm, clusteredSE, haltonBase, haltonBurnin, haltonUi0Base, scrambledHalton, shuffledHalton, confInt, decimalPlaces, consoleWidth, idColName, timeColName);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_sfacpp_sfacpp_internal", (DL_FUNC) &_sfacpp_sfacpp_internal, 41},
    {"_sfacpp_sfacpp_internal_searches", (DL_FUNC) &_sfacpp_sfacpp_internal_searches, 27},
    {"_sfacpp_sfacpp_internal_lrtest", (DL_FUNC) &_sfacpp_sfacpp_internal_lrtest, 5},
    {"_sfacpp_sfacpp_internal_call_print_model_summary", (DL_FUNC) &_sfacpp_sfacpp_internal_call_print_model_summary, 23},
    {NULL, NULL, 0}
};

RcppExport void R_init_sfacpp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
