# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sfacpp_internal <- function(y_, allData_, colCounts_, idVec_ = NULL, timeVec_ = NULL, startVals_ = NULL, prodCost = 1L, model = "tre", dist = "hnorm", method = "tr", methodLib = "dlib", marginalEffect = "wang2002", optimOpts = NULL, termsX_ = NULL, termsZmuit_ = NULL, termsZuit_ = NULL, termsZvit_ = NULL, termsZui0_ = NULL, termsZvi0_ = NULL, nsim = 100L, hessianCalc = "analytical", hessianCalcNumApproxAccuracy = 3L, seed = 1234L, confidenceLevel = 0.95, estimateMarginalEffects = FALSE, estimateMargEffCI = FALSE, marginalEffectBootstrapReps = 500L, printLevel = 2L, clusteredSE = FALSE, haltonBase = 2L, haltonBurnin = 1000L, haltonUi0Base = 3L, scrambledHalton = TRUE, shuffledHalton = FALSE, nthreads = 20L, calculateEfficiencyScores = FALSE, ghkSimReps = 2000L, displayDecimalPlaces = 5L, displayConsoleWidth = 120L, idColName = NULL, timeColName = NULL) {
    .Call(`_sfacpp_sfacpp_internal`, y_, allData_, colCounts_, idVec_, timeVec_, startVals_, prodCost, model, dist, method, methodLib, marginalEffect, optimOpts, termsX_, termsZmuit_, termsZuit_, termsZvit_, termsZui0_, termsZvi0_, nsim, hessianCalc, hessianCalcNumApproxAccuracy, seed, confidenceLevel, estimateMarginalEffects, estimateMargEffCI, marginalEffectBootstrapReps, printLevel, clusteredSE, haltonBase, haltonBurnin, haltonUi0Base, scrambledHalton, shuffledHalton, nthreads, calculateEfficiencyScores, ghkSimReps, displayDecimalPlaces, displayConsoleWidth, idColName, timeColName)
}

sfacpp_internal_searches <- function(y_, allData_, colCounts_, idVec_ = NULL, timeVec_ = NULL, startVals_ = NULL, reps = 500L, maxRepIter = 100L, slengthFrontier = 2.0, slengthSigmas = 0.8, maxStartValFindAttempt = 50L, prodCost = 1L, model = "tre", dist = "hnorm", method = "tr", methodLib = "dlib", nsim = 100L, seed = 1234L, printLevel = 0L, nthreads = 20L, haltonBase = 2L, haltonBurnin = 1000L, haltonUi0Base = 3L, scrambledHalton = TRUE, shuffledHalton = FALSE, displayConsoleWidth = 120L, displayDecimalPlaces = 4L) {
    .Call(`_sfacpp_sfacpp_internal_searches`, y_, allData_, colCounts_, idVec_, timeVec_, startVals_, reps, maxRepIter, slengthFrontier, slengthSigmas, maxStartValFindAttempt, prodCost, model, dist, method, methodLib, nsim, seed, printLevel, nthreads, haltonBase, haltonBurnin, haltonUi0Base, scrambledHalton, shuffledHalton, displayConsoleWidth, displayDecimalPlaces)
}

sfacpp_internal_lrtest <- function(ll0, ll1, nparam0, nparam1, dp = 5) {
    .Call(`_sfacpp_sfacpp_internal_lrtest`, ll0, ll1, nparam0, nparam1, dp)
}

sfacpp_internal_call_print_model_summary <- function(model, dist, nobs, nids, maxT, minT, modelSummaryIn, modelSummaryTerms, sigmaParams, nsim, llscore, gnorm, clusteredSE, haltonBase, haltonBurnin, haltonUi0Base, scrambledHalton, shuffledHalton, confInt, decimalPlaces, consoleWidth, idColName = NULL, timeColName = NULL) {
    invisible(.Call(`_sfacpp_sfacpp_internal_call_print_model_summary`, model, dist, nobs, nids, maxT, minT, modelSummaryIn, modelSummaryTerms, sigmaParams, nsim, llscore, gnorm, clusteredSE, haltonBase, haltonBurnin, haltonUi0Base, scrambledHalton, shuffledHalton, confInt, decimalPlaces, consoleWidth, idColName, timeColName))
}

